Hw_2_Sotnikov
Asklepiad/Python_BI_2022 pull request #1
Opened 2022-09-27 15:26 UTC by Asklepiad

Сдача домашнего задания №2. 
Студент Богдан Сотников.

2022-10-15 19:09 UTC, krglkvrmn requested changes
Привет, хорошая работа, комментарии ниже)

2022-10-15 19:09 UTC, krglkvrmn commented on README.md
> +# Python_BI_2022
Ридми огонь, только лучше добавлять побольше маркдауна к тексту. Например, команды можно выделять `как код` или **жирным шрифтом**. Если нужно на чём-то акцентировать внимание, то можно влепить какой-нибудь яркий эмодзи❗❗❗.

2022-10-15 19:09 UTC, krglkvrmn commented on hw_2/hw2_Sotnikov.py
> +                print(rna2dna[nucleotide], end="")
А, ну и это уже обратная транскрипция, стоило или сделать отдельную опцию или предупредить юзера

2022-10-24 08:45 UTC, Asklepiad commented on hw_2/hw2_Sotnikov.py
> +    return(nucl_acid, nucl_type)
Понял, исправляюсь. Это артефакт после R .

2022-10-24 08:45 UTC, Asklepiad commented on README.md
> +![Entering commands](/hw_2/1print.png)
Понял, учту на будущее. В третьей домашке, правда, та же проблема, так как сдал ее раньше, чем сел читать замечания к предыдущим (планировал несколько более основательно проработать замечания).

2022-10-24 08:46 UTC, merged